### ISSUE TITLE
  error: command 'x86_64-linux-gnu-gcc' failed

### ISSUE THREAD

**Issue by kuamit5516** [nihal111/J.A.R.V.I.S#10]
root@root:~/J.A.R.V.I.S# pip install -r requirements.txt
Requirement already satisfied: aiml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (0.9.1)
Requirement already satisfied: SpeechRecognition in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (3.6.3)
Collecting pyalsaaudio (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/52/b6/44871791929d9d7e11325af0b7be711388dfeeab17147988f044a41a6d83/pyalsaaudio-0.8.4.tar.gz
Collecting pyttsx (from -r requirements.txt (line 4))
Collecting gTTS (from -r requirements.txt (line 5))
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages/setuptools-27.3.0.post20180517-py2.7.egg (from aiml->-r requirements.txt (line 1)) (27.3.0.post20180517)
Requirement already satisfied: bs4 in /usr/local/lib/python2.7/dist-packages (from gTTS->-r requirements.txt (line 5)) (0.0.1)
Requirement already satisfied: click in /usr/lib/python2.7/dist-packages (from gTTS->-r requirements.txt (line 5)) (6.7)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from gTTS->-r requirements.txt (line 5)) (1.10.0)
Collecting gtts-token (from gTTS->-r requirements.txt (line 5))
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from gTTS->-r requirements.txt (line 5)) (2.13.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from bs4->gTTS->-r requirements.txt (line 5)) (4.5.3)
Building wheels for collected packages: pyalsaaudio
  Running setup.py bdist_wheel for pyalsaaudio ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-_ihyGR/pyalsaaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-svNPlI --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'alsaaudio' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-m2Tzf3/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c alsaaudio.c -o build/temp.linux-x86_64-2.7/alsaaudio.o
  alsaaudio.c:28:10: fatal error: alsa/asoundlib.h: No such file or directory
   #include <alsa/asoundlib.h>
            ^~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyalsaaudio
  Running setup.py clean for pyalsaaudio
Failed to build pyalsaaudio
Installing collected packages: pyalsaaudio, pyttsx, gtts-token, gTTS
  Running setup.py install for pyalsaaudio ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-_ihyGR/pyalsaaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-BeGGQI/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'alsaaudio' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-m2Tzf3/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c alsaaudio.c -o build/temp.linux-x86_64-2.7/alsaaudio.o
    alsaaudio.c:28:10: fatal error: alsa/asoundlib.h: No such file or directory
     #include <alsa/asoundlib.h>
              ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-_ihyGR/pyalsaaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-BeGGQI/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-_ihyGR/pyalsaaudio/

**Comment by nihal111** [comment]
Ref: https://github.com/SlapBot/stephanie-va/issues/8
Can you try: `sudo apt install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 ffmpeg libav-tools`
Also please try solutions listed here- https://stackoverflow.com/questions/26053982/setup-script-exited-with-error-command-x86-64-linux-gnu-gcc-failed-with-exit

**Comment by kuamit5516** [comment]
:~# sudo apt install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 ffmpeg libav-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libasound2-dev' instead of 'libasound-dev'
Package libav-tools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  ffmpeg

E: Package 'libav-tools' has no installation candidate


plz help - 

Thanx - Advance

**Comment by nihal111** [comment]
@kuamit5516 what OS are you using? ffmpeg and libav-tools are often replaced by one another in ubuntu. Ref: https://stackoverflow.com/questions/9477115/what-are-the-differences-and-similarities-between-ffmpeg-libav-and-avconv

Did installing ffmpeg along with those other packages allow pyalsaaudio to install successfully?

**Comment by kuamit5516** [comment]
Dude -Thanks again
 
Bro Im use this version - kali-linux-2018.2-amd64.iso ...usb boot install....


:~# apt-get install ffmpeg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ffmpeg is already the newest version (7:3.4.2-2+b1).
The following packages were automatically installed and are no longer required:
  libfile-copy-recursive-perl libhttp-parser2.7.1 libqgis-analysis2.18.17
  libqgis-core2.18.17 libqgis-gui2.18.17 libqgis-networkanalysis2.18.17
  libqgis-server2.18.17 libqgispython2.18.17 libsynctex1 libtcl8.5 libtk8.5
  openjdk-9-jdk openjdk-9-jdk-headless openjdk-9-jre pepperflashplugin-nonfree
  python-unicodecsv python3-h11 tk8.5
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

2nd Try - 

:~# ffmpeg
ffmpeg version 3.4.2-2+b1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Debian 7.3.0-16)
  configuration: --prefix=/usr --extra-version=2+b1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'


Bro 'man ffmpeg' how use easly  - plz help and tech me . 


# **Im also update & upgrade my system - but i face different-different error's ,**


sudo apt-get update :-: Result 

:~# sudo apt-get update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:2 http://dl.google.com/linux/chrome/deb stable Release                     
Hit:3 http://download.virtualbox.org/virtualbox/debian stretch InRelease       
Ign:5 https://deb.nodesource.com/node_6.x kali-rolling InRelease               
Get:6 https://deb.opera.com/opera-stable stable InRelease [2,592 B]            
Err:7 https://deb.nodesource.com/node_6.x kali-rolling Release                 
  404  Not Found [IP: 2600:9000:2046:9800:1f:6523:6040:93a1 443]
Get:8 https://deb.opera.com/opera-stable stable/non-free amd64 Packages [1,804 B]
Ign:9 http://download.virtualbox.org/virtualbox/debian kali-rolling InRelease  
Err:10 http://download.virtualbox.org/virtualbox/debian kali-rolling Release   
  404  Not Found [IP: 49.44.170.160 80]
Get:11 http://http.kali.org/kali kali-rolling InRelease [30.5 kB]              
Get:12 http://archive.kali.org/kali kali-rolling/main amd64 Packages [16.0 MB] 
Get:13 http://archive.kali.org/kali kali-rolling/non-free amd64 Packages [166 kB]
Err:13 http://archive.kali.org/kali kali-rolling/non-free amd64 Packages       
  File has unexpected size (166161 != 166158). Mirror sync in progress? [IP: 192.99.45.140 80]
  Hashes of expected file:
   - Filesize:166158 [weak]
   - SHA256:d788ca20021deb2c257a2fc427106694cb23a7e880d4898a29d0b8841bfc41e0
   - SHA1:e80137e8e2f047030f34a33a98d9c7f932217641 [weak]
   - MD5Sum:6db5c1e9bebd92c4f1d1ee1b4eb27924 [weak]
  Release file created at: Tue, 22 May 2018 00:07:52 +0000
Reading package lists... Done                                                  
E: The repository 'https://deb.nodesource.com/node_6.x kali-rolling Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://download.virtualbox.org/virtualbox/debian kali-rolling Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.



sudo apt-get upgrade :-: Result 

:~# sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libfile-copy-recursive-perl libhttp-parser2.7.1 libqgis-analysis2.18.17
  libqgis-core2.18.17 libqgis-gui2.18.17 libqgis-networkanalysis2.18.17
  libqgis-server2.18.17 libqgispython2.18.17 libsynctex1 libtcl8.5 libtk8.5
  openjdk-9-jdk openjdk-9-jdk-headless openjdk-9-jre pepperflashplugin-nonfree
  python-unicodecsv python3-h11 tk8.5
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

.

Advance Thanks ...
