### ISSUE TITLE
its not work 

### ISSUE THREAD

**Issue by pce16ec045** [nihal111/J.A.R.V.I.S#11]
its show as

>>>root@KALI:~/Downloads/J.A.R.V.I.S-master# python script.py --voice
Loading std-startup.xml...done (0.00 seconds)
Loading launching_programs.aiml...done (0.00 seconds)
Loading basic_chat.aiml...done (0.00 seconds)
Loading music_controls.aiml...done (0.00 seconds)
Loading search_internet.aiml...done (0.00 seconds)
Loading wallpaper.aiml...done (0.00 seconds)
Loading volume_controls.aiml...done (0.00 seconds)

Kernel bootstrap completed in 0.02 seconds
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Talk to J.A.R.V.I.S:

**Comment by nihal111** [comment]
Did you try writing something after it says "Talk to J.A.R.V.I.S:"? :)

**Comment by pce16ec045** [comment]
no

**Comment by nihal111** [comment]
Please do that.

**Comment by pce16ec045** [comment]
its not work... :(

**Comment by nihal111** [comment]
Not helping. Please paste the error you get when you type"Hello" and hit Enter when the screen reads "Talk to J.A.R.V.I.S:".

**Comment by pce16ec045** [comment]
root@KALI:~/Downloads/J.A.R.V.I.S-master# python script.py --voice
Loading std-startup.xml...done (0.00 seconds)
Loading launching_programs.aiml...done (0.00 seconds)
Loading basic_chat.aiml...done (0.00 seconds)
Loading music_controls.aiml...done (0.00 seconds)
Loading search_internet.aiml...done (0.00 seconds)
Loading wallpaper.aiml...done (0.00 seconds)
Loading volume_controls.aiml...done (0.00 seconds)

Kernel bootstrap completed in 0.02 seconds
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Talk to J.A.R.V.I.S: 
hello

**Comment by pce16ec045** [comment]
no changes on terminal

**Comment by pce16ec045** [comment]
yas i install all dependencies

**Comment by nihal111** [comment]
Please do not use the comment thread as a chat. I'll refrain from replying if your comments don't add any value or information to the conversation.

**Comment by pce16ec045** [comment]
root@KALI:~/Downloads/J.A.R.V.I.S-master# pip install -r requirements.txt
Requirement already satisfied: argparse in /usr/lib/python2.7 (from -r requirements.txt (line 1))
Requirement already satisfied: aiml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: SpeechRecognition in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: pyalsaaudio in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: pyttsx in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: pyaudio in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: gTTS in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: pygame in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from aiml->-r requirements.txt (line 2))
Requirement already satisfied: bs4 in /usr/local/lib/python2.7/dist-packages (from gTTS->-r requirements.txt (line 7))
Requirement already satisfied: click in /usr/lib/python2.7/dist-packages (from gTTS->-r requirements.txt (line 7))
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from gTTS->-r requirements.txt (line 7))
Requirement already satisfied: gtts-token in /usr/local/lib/python2.7/dist-packages (from gTTS->-r requirements.txt (line 7))
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from gTTS->-r requirements.txt (line 7))
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages (from bs4->gTTS->-r requirements.txt (line 7))
root@KALI:~/Downloads/J.A.R.V.I.S-master# 
see.............

**Comment by pce16ec045** [comment]
ok sorry bro.... can you plz give your num  or.... any contect....
