### ISSUE TITLE
pyalsaaudio issue

### ISSUE THREAD

**Issue by whatnowangga** [nihal111/J.A.R.V.I.S#17]
> pi@raspberrypi:~/Desktop/jarvis $ pip install pyalsaaudio
Collecting pyalsaaudio
  Using cached https://files.pythonhosted.org/packages/52/b6/44871791929d9d7e11325af0b7be711388dfeeab17147988f044a41a6d83/pyalsaaudio-0.8.4.tar.gz
Building wheels for collected packages: pyalsaaudio
  Running setup.py bdist_wheel for pyalsaaudio ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-IFzze4/pyalsaaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpUcPcPppip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'alsaaudio' extension
  creating build
  creating build/temp.linux-armv7l-2.7
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Ub3vap/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c alsaaudio.c -o build/temp.linux-armv7l-2.7/alsaaudio.o
  alsaaudio.c:28:28: fatal error: alsa/asoundlib.h: No such file or directory
   #include <alsa/asoundlib.h>
                              ^
  compilation terminated.
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyalsaaudio
  Running setup.py clean for pyalsaaudio
Failed to build pyalsaaudio
Installing collected packages: pyalsaaudio
  Running setup.py install for pyalsaaudio ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-IFzze4/pyalsaaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-jQc1UV-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_ext
    building 'alsaaudio' extension
    creating build
    creating build/temp.linux-armv7l-2.7
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Ub3vap/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c alsaaudio.c -o build/temp.linux-armv7l-2.7/alsaaudio.o
    alsaaudio.c:28:28: fatal error: alsa/asoundlib.h: No such file or directory
     #include <alsa/asoundlib.h>
                                ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-IFzze4/pyalsaaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-jQc1UV-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-IFzze4/pyalsaaudio/

**Comment by whatnowangga** [comment]
SOLVED
I have had to install “libasound2-dev” as a pre-requisite on my raspberry pi

**Comment by AemanShah** [comment]
is pyalsaaudio is for linux OS ?
