### ISSUE TITLE
errror

### ISSUE THREAD

**Issue by prad-33-p** [nihal111/J.A.R.V.I.S#8]
root@kali:~/J.A.R.V.I.S# ./script.py voice
Loading std-startup.xml... done (0.00 seconds)
Loading basic_chat.aiml... done (0.00 seconds)
Loading search_internet.aiml... done (0.00 seconds)
Loading music_controls.aiml... done (0.00 seconds)
Loading volume_controls.aiml... done (0.00 seconds)
Loading launching_programs.aiml... done (0.01 seconds)
Loading wallpaper.aiml... done (0.00 seconds)

Kernel bootstrap completed in 0.03 seconds
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Talk to J.A.R.V.I.S:

**Comment by nihal111** [comment]
Looks like pyalsaaudio couldn't recognize your audio card. Hard to say what the issue might be.

**Comment by nihal111** [comment]
Closing now, reopen if issue persists.
